#!/usr/bin/env python3
"""Extract ToonTalk resource strings into a JS table for the WASM LoadStringA shim.

The native build compiles STRINGTABLEs from a custom `SYMBOL,\n"value"` pair format
(see static.rc / english.rc). strings.h maps each SYMBOL to a unique numeric id. At
runtime LoadString(module, id, ...) fetches by number. We merge every English/neutral
string source into ONE {id: "value"} table (ids are globally unique, so the module
arg is irrelevant) and emit it as an emscripten JS-library data symbol $TT_RES_STRINGS.
"""
import re, json, os

SRC       = r"C:\Users\toont\dev\source"
STRINGS_H = r"C:\Users\toont\dev\tt-wasm\src\strings.h"
OUT       = r"C:\Users\toont\dev\tt-wasm\shim\resstrings.js"

# Order: UI/aux first, then static/debug last so the exe's authoritative table wins on any dup.
RC_FILES = ["english.rc", "new.rc", "puzzle.rc", "sensors.rc", "sound.rc",
            "common.rc", "extra.rc", "debug.rc", "static.rc"]

def read(path):
    with open(path, encoding="latin-1") as f:
        return f.readlines()

# 1) strings.h : #define SYMBOL <number>
sym2num = {}
defre = re.compile(r'^\s*#define\s+([A-Za-z_]\w*)\s+(\d+)\b')
for line in read(STRINGS_H):
    m = defre.match(line)
    if m:
        sym2num[m.group(1)] = int(m.group(2))

# 2) each .rc : pair a `SYMBOL,` line with the following `"value"` line
symline = re.compile(r'^\s*([A-Za-z_]\w*)\s*,\s*(?://.*)?$')
strline = re.compile(r'^\s*"(.*)"\s*(?://.*)?$')

num2str, dups, unknown = {}, 0, 0
for rc in RC_FILES:
    path = os.path.join(SRC, rc)
    if not os.path.exists(path):
        print(f"  (missing {rc})")
        continue
    pending = None
    for raw in read(path):
        s = raw.rstrip("\n")
        st = s.strip()
        if st == "" or st.startswith("#") or st.startswith("//") \
           or st.startswith("STRINGTABLE") or st in ("{", "}"):
            continue
        ms = symline.match(s)
        if ms:
            pending = ms.group(1)
            continue
        mv = strline.match(s)
        if mv and pending is not None:
            sym, val = pending, mv.group(1)
            pending = None
            n = sym2num.get(sym)
            if n is None:
                unknown += 1
                continue
            if n in num2str:
                dups += 1
            num2str[n] = val
            continue
        pending = None

# 3) emit JS library data symbol
items = ",\n".join(f"    {n}: {json.dumps(v)}" for n, v in sorted(num2str.items()))
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by tools/extract_resources.py from ToonTalk .rc STRINGTABLEs.\n")
    f.write("// Maps numeric resource id -> string; consumed by LoadStringA in overrides.js.\n")
    f.write("addToLibrary({\n  $TT_RES_STRINGS: {\n")
    f.write(items)
    f.write("\n  }\n});\n")

print(f"strings.h symbols : {len(sym2num)}")
print(f"resource strings  : {len(num2str)}  (dups={dups}, unknown-symbol pairs skipped={unknown})")
for k in ("IDC_TT_INI", "IDS_MAIN_DIR", "IDC_DIRECTORIES", "IDC_CLIPPING_DIR"):
    n = sym2num.get(k)
    print(f"  {k} = {n} -> {num2str.get(n)!r}")
print(f"wrote {OUT}")
