"""Regenerate shim/resstrings.js from the SHIPPED string table.

The table was previously generated from the .rc sources. Those are the development sources; the
STRINGTABLE inside USVer22.dll is what ToonTalk actually shipped, and the two disagree:

  - 312 ids exist only in the DLL (Marty's description fragments -- 'pictures of', 'stacks of ',
    'the movie of' -- so those readings came out wrong or empty);
  - 125 shared ids differ, nearly all because the .rc route turned a carriage return into a
    LITERAL backslash-r. "Person\\rWalk" was reaching the screen with the escape visible instead
    of breaking the line.

So the DLL wins wherever it has an id, and .rc entries are kept only for ids the DLL lacks (the
engine does ask for a few that were never shipped -- 2574 and 2575 are absent from both, which is
why the log warns about them; that warning is not a port defect).

    python tools/gen_resstrings.py <path-to-USVer22.dll>
"""
import json, re, io, os, struct, sys


def extract_pe_strings(path):
    d = open(path, 'rb').read()
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    if d[pe:pe + 4] != b'PE\0\0':
        raise SystemExit('not a PE file: ' + path)
    nsec = struct.unpack_from('<H', d, pe + 6)[0]
    optsz = struct.unpack_from('<H', d, pe + 20)[0]
    magic = struct.unpack_from('<H', d, pe + 24)[0]
    ddoff = pe + 24 + (96 if magic == 0x10b else 112)
    rva, _ = struct.unpack_from('<II', d, ddoff + 2 * 8)      # data directory 2 = resources
    secs = []
    so = pe + 24 + optsz
    for i in range(nsec):
        vs, va, rs, pr = struct.unpack_from('<IIII', d, so + i * 40 + 8)
        secs.append((va, vs, pr, rs))

    def to_off(r):
        for va, vs, pr, rs in secs:
            if va <= r < va + max(vs, rs):
                return pr + (r - va)
        return None

    base = to_off(rva)

    def entries(off):
        nn, ni = struct.unpack_from('<HH', d, off + 12)
        return [struct.unpack_from('<II', d, off + 16 + i * 8) for i in range(nn + ni)]

    out = {}
    for eid, offs in entries(base):
        if (eid & 0x7fffffff) != 6:                           # RT_STRING
            continue
        for nid, noff in entries(base + (offs & 0x7fffffff)):
            block = nid & 0x7fffffff                          # 16 strings per block
            for _lid, loff in entries(base + (noff & 0x7fffffff)):
                drva, dsz = struct.unpack_from('<II', d, base + (loff & 0x7fffffff))
                o = to_off(drva)
                end = o + dsz
                idx = (block - 1) * 16
                while o < end:
                    ln = struct.unpack_from('<H', d, o)[0]
                    o += 2
                    s = d[o:o + ln * 2].decode('utf-16-le', 'replace')
                    o += ln * 2
                    if s:
                        out[idx] = s
                    idx += 1
                break                                          # first language only
    return out


def parse_existing(path):
    src = io.open(path, encoding='utf-8').read()
    pat = re.compile(r'^\s*(\d+):\s*"((?:\\.|[^"\\])*)"', re.M)
    out = {}
    for m in pat.finditer(src):
        raw, res, i = m.group(2), [], 0
        while i < len(raw):
            c = raw[i]
            if c == '\\' and i + 1 < len(raw):
                n = raw[i + 1]
                res.append({'n': '\n', 'r': '\r', 't': '\t', '"': '"', '\\': '\\'}.get(n, n))
                i += 2
            else:
                res.append(c)
                i += 1
        out[int(m.group(1))] = ''.join(res)
    return out


def js_quote(s):
    out = []
    for ch in s:
        if ch == '\\':   out.append('\\\\')
        elif ch == '"':  out.append('\\"')
        elif ch == '\r': out.append('\\r')
        elif ch == '\n': out.append('\\n')
        elif ch == '\t': out.append('\\t')
        elif ord(ch) < 0x20 or ord(ch) > 0x7e: out.append('\\u%04x' % ord(ch))
        else: out.append(ch)
    return '"' + ''.join(out) + '"'


def main():
    dll = sys.argv[1] if len(sys.argv) > 1 else \
        r"C:\Program Files (x86)\Animated Programs\ToonTalk\USVer22.dll"
    shipped = extract_pe_strings(dll)
    old = parse_existing('shim/resstrings.js')
    merged = dict(old)
    merged.update(shipped)                                     # shipped wins
    only_old = sorted(set(old) - set(shipped))
    print('shipped %d, previous %d, merged %d (kept %d ids the shipped table lacks)'
          % (len(shipped), len(old), len(merged), len(only_old)))

    lines = [
        '// AUTO-GENERATED by tools/gen_resstrings.py from the SHIPPED STRINGTABLE in USVer22.dll,',
        '// with the .rc-derived table underneath for the few ids the shipped build never had.',
        '// Maps numeric resource id -> string; consumed by LoadStringA in overrides.js.',
        'addToLibrary({',
        '  $TT_RES_STRINGS: {',
    ]
    for k in sorted(merged):
        lines.append('    %d: %s,' % (k, js_quote(merged[k])))
    lines += ['  },', '});', '']
    io.open('shim/resstrings.js', 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    print('wrote shim/resstrings.js')


if __name__ == '__main__':
    main()
