#!/usr/bin/env python3
"""Generate shim/gdi_font.h — a tiny bitmap font for the GDI shim's TextOut.

Renders ASCII 32..126 with Pillow's built-in bitmap font into an 8xH bit-mask per
glyph (MSB = leftmost pixel). The shim integer-scales glyphs up to the requested
LOGFONT height, which keeps ToonTalk's balloons/pads/labels legible without shipping
a real font engine.
"""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(__file__), "..", "shim", "gdi_font.h")
font = ImageFont.load_default()

# measure a cell that fits every glyph
maxw = maxh = 0
for c in range(32, 127):
    bbox = font.getbbox(chr(c))
    maxw = max(maxw, bbox[2])
    maxh = max(maxh, bbox[3])
W, H = min(maxw, 8), maxh

rows_per_glyph = []
for c in range(32, 127):
    im = Image.new("1", (8, H), 0)
    ImageDraw.Draw(im).text((0, 0), chr(c), fill=1, font=font)
    px = im.load()
    rows = []
    for y in range(H):
        bits = 0
        for x in range(8):
            if px[x, y]:
                bits |= 0x80 >> x
        rows.append(bits)
    rows_per_glyph.append(rows)

with open(OUT, "w", newline="\n") as f:
    f.write("/* AUTO-GENERATED by tools/make_font.py — ASCII 32..126, %dx%d bitmap font\n"
            " * (Pillow default font). Row bytes, MSB = leftmost pixel. */\n" % (W, H))
    f.write("#define TT_FONT_W %d\n#define TT_FONT_H %d\n" % (W, H))
    f.write("static const unsigned char tt_font[95][%d] = {\n" % H)
    for i, rows in enumerate(rows_per_glyph):
        ch = chr(32 + i)
        label = ch if ch not in "\\'" else " "
        f.write("  {%s}, /* '%s' */\n" % (",".join("0x%02X" % b for b in rows), label))
    f.write("};\n")
print("wrote", OUT, "cell %dx%d" % (W, H))
