#!/usr/bin/env python3
"""Generate shim/gdi_font.h — bitmap fonts for the GDI shim's TextOut (ASCII+Latin-1, 32..255).

Renders ASCII 32..126 from a real vector font (Arial, from the Windows fonts
directory) at THREE base cell sizes. The shim picks the largest base that fits
the requested LOGFONT height and integer-scales the remainder, so pad digits,
balloon text, and labels stay legible at any size — the Pillow built-in font
the first version used had digits that scaled into unreadable blobs
(a '1' read as a 5; Ken's "the numbers weren't visible").

Each glyph row is a bit mask, MSB = leftmost pixel; 8-wide cells use one byte
per row, 16-wide use uint16, 32-wide use uint32.
"""
import os
from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(os.path.dirname(__file__), "..", "shim", "gdi_font.h")
TTF = r"C:\Windows\Fonts\arialbd.ttf"   # bold reads better at small sizes on 8-bit surfaces

# (cell_w, cell_h, point_size, C type, name suffix)
SIZES = [(8, 12, 11, "unsigned char", "8"),
         (16, 24, 22, "unsigned short", "16"),
         (32, 48, 44, "unsigned int", "32")]


def render(cell_w, cell_h, pt):
    font = ImageFont.truetype(TTF, pt)
    ascent, descent = font.getmetrics()
    rows_per_glyph = []
    for c in range(32, 256):
        im = Image.new("1", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(im)
        ch = chr(c)
        bbox = d.textbbox((0, 0), ch, font=font)
        # center horizontally in the cell; sit the baseline consistently
        x = max(0, (cell_w - (bbox[2] - bbox[0])) // 2 - bbox[0])
        y = cell_h - descent - ascent
        d.text((x, y), ch, fill=1, font=font)
        px = im.load()
        rows = []
        for yy in range(cell_h):
            bits = 0
            for xx in range(cell_w):
                if px[xx, yy]:
                    bits |= (1 << (cell_w - 1)) >> xx
            rows.append(bits)
        rows_per_glyph.append(rows)
    return rows_per_glyph


with open(OUT, "w", newline="\n") as f:
    f.write("/* AUTO-GENERATED by tools/make_font.py — ASCII 32..126 from Arial Bold at three\n"
            " * base sizes. Row bit-masks, MSB = leftmost pixel. The shim picks the largest\n"
            " * base <= the requested height and integer-scales the remainder. */\n")
    for cell_w, cell_h, pt, ctype, suffix in SIZES:
        rows_all = render(cell_w, cell_h, pt)
        f.write("#define TT_FONT%s_W %d\n#define TT_FONT%s_H %d\n" % (suffix, cell_w, suffix, cell_h))
        f.write("static const %s tt_font%s[224][%d] = {\n" % (ctype, suffix, cell_h))
        hexw = cell_w // 4
        for i, rows in enumerate(rows_all):
            ch = chr(32 + i)
            label = ch if (32 + i < 127 and ch not in "\'") else ("x%02X" % (32 + i))
            f.write("  {%s}, /* '%s' */\n" % (",".join("0x%0*X" % (hexw, b) for b in rows), label))
        f.write("};\n")
    # compatibility aliases for existing shim code
    f.write("#define TT_FONT_W TT_FONT8_W\n#define TT_FONT_H TT_FONT8_H\n"
            "#define tt_font tt_font8\n")
print("wrote", OUT)
