#!/usr/bin/env bash
# Link the ToonTalk WASM engine.
#   usage: bash link.sh                 # normal build
#          bash link.sh "-sSAFE_HEAP=1 -g2"   # debug build (catches bad memory access, named frames)
#
# stubs.js is AUTO-GENERATED here as (all_imports.txt) minus (functions overrides.js defines),
# so the only file to hand-edit is shim/overrides.js — add a functional stub there and the
# corresponding zero-stub disappears from stubs.js automatically (no dup-symbol link error).
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"; cd "$HERE" || exit 1
EMCC=/c/Users/toont/dev/emsdk/upstream/emscripten/emcc.exe
mkdir -p build logs .tmp

# Keep every temp file emcc/node generate inside .tmp instead of %TEMP%.
# Reason: emcc runs file_packager, writes its ~105KB generated asset-loader JS to a temp file and
# feeds it back to the JS compiler as a pre-js.  Windows Defender's ML heuristic
# (Trojan:Script/ObfusScript.A!ml, threat 2147842389) false-positives on that generated blob, so
# node's readFileSync fails with an opaque "UNKNOWN: unknown error, open ...tmpXXXX.js" and the
# whole link dies with "Internal compiler error JS compiler".  Concentrating the temp files here
# means the Defender exclusion needed to build is ONE project folder rather than all of %TEMP%.
export TMPDIR="$HERE/.tmp" TEMP="$HERE/.tmp" TMP="$HERE/.tmp"

# 0. compile the shim .cpp that carry real code (COM data symbols, entry, MSXML DOM) into obj/
for s in guids diformats entry msxml_impl ddraw_impl gdi_impl dunzip_impl dzip_impl dsound_impl png_impl mmio_impl; do
  if [ "shim/$s.cpp" -nt "obj/$s.o" ] || [ ! -f "obj/$s.o" ]; then
    echo "compiling shim/$s.cpp"
    "$EMCC" -std=gnu++14 -fwasm-exceptions -w -DWIN32 -sUSE_ZLIB=1 -c "shim/$s.cpp" -o "obj/$s.o" -I shim -I src 2>"logs/$s.err" \
      || { echo "SHIM COMPILE FAILED: $s"; tail -25 "logs/$s.err"; exit 1; }
  fi
done
# 0b. real bignum arithmetic: mini-gmp/mini-mpq (C, -O2 — rational math is hot)
for s in mini-gmp mini-mpq gmp_extra; do
  if [ "shim/$s.c" -nt "obj/$s.o" ] || [ ! -f "obj/$s.o" ]; then
    echo "compiling shim/$s.c"
    "$EMCC" -w -O2 -c "shim/$s.c" -o "obj/$s.o" -I shim 2>"logs/$s.err" \
      || { echo "SHIM COMPILE FAILED: $s"; tail -25 "logs/$s.err"; exit 1; }
  fi
done

# 1. regenerate stubs.js = all imports NOT implemented in overrides.js OR in shim/*.cpp (cdefined.txt)
KEYS=$(grep -oE '^[[:space:]]+[A-Za-z_][A-Za-z0-9_]*[[:space:]]*:' shim/overrides.js | tr -d ' :' | sort -u)
CDEF=$(cat shim/cdefined.txt 2>/dev/null)
KEYPAT=$(printf '%s\n%s\n' "$KEYS" "$CDEF" | grep -v '^[[:space:]]*$' | tr '\n' '|' | sed 's/|$//')
{
  echo "// AUTO-GENERATED by link.sh = all_imports.txt minus overrides.js keys. Edit overrides.js, not this."
  echo "addToLibrary({"
  awk 'NF{print $1}' all_imports.txt | grep -vE "^(${KEYPAT})$" | sed 's/^/  /; s/$/: function(){ return 0; },/'
  echo "});"
} > shim/stubs.js
echo "stubs.js: $(grep -c 'function' shim/stubs.js) zero-stubs | overrides.js: $(echo "$KEYS" | wc -w) functional"

# 2. link engine objects (all obj/*.o except the separate programs)
OBJS=$(ls obj/*.o | grep -vE '/(Dll|Starttt|clickme)\.o$')
EXTRA="${1:-}"
"$EMCC" $OBJS \
  --js-library shim/stubs.js --js-library shim/overrides.js --js-library shim/resstrings.js \
  --pre-js shim/pre.js \
  --preload-file assets/toontalk@/toontalk \
  --preload-file assets/pics@/toontalk/pics \
  -fwasm-exceptions \
  -sERROR_ON_UNDEFINED_SYMBOLS=0 -Wl,--allow-multiple-definition \
  -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=67108864 \
  -sSTACK_SIZE=16777216 \
  -sUSE_ZLIB=1 -lidbfs.js -sASSERTIONS=2 $EXTRA -o build/tt.js 2>logs/link.err
rc=$?; echo "link exit=$rc"
if [ $rc -ne 0 ] && grep -q "UNKNOWN: unknown error, open" logs/link.err; then
  # Don't let this one masquerade as a code error again -- emcc reports it as
  # "Internal compiler error JS compiler", which sends you hunting through the shim for hours.
  echo "*** This is NOT a code error: Windows Defender is blocking the asset-loader JS that"
  echo "*** emcc generates (false positive Trojan:Script/ObfusScript.A!ml, threat 2147842389)."
  echo "*** Fix: add a Defender FOLDER exclusion for   $HERE/.tmp"
  echo "*** (Windows Security > Virus & threat protection > Manage settings > Exclusions),"
  echo "*** and consider submitting the file to Microsoft as a false positive."
fi
[ $rc -ne 0 ] && { echo "--- link errors ---"; tail -30 logs/link.err; exit 1; }
# The recorded .dmo demos (~36MB) are served over HTTP rather than preloaded into tt.data —
# pre.js fetches the one named by ?demo=<name>. Mirror them from the retail install if present
# (same provenance as the art; deliberately not kept in the repo).
DEMOSRC="/c/Program Files (x86)/Animated Programs/ToonTalk/Demos/US"
if [ -d "$DEMOSRC" ]; then
  mkdir -p build/demos
  for d in "$DEMOSRC"/*.dmo; do
    [ -e "$d" ] || continue
    b=$(basename "$d")
    [ -f "build/demos/$b" ] || cp "$d" "build/demos/$b"
  done
fi
# The Playground city and notebook that shipped with the retail product (Users/Playground2001X,
# Users/PlaygroundBookX). Served over HTTP like the demos rather than packed into tt.data: the two
# XML files alone are 9.1MB and 8.3MB, and only a player who asks for the Playground needs them.
# pre.js fetches one on demand for ?user=<name>. The .url sidecars are the original's own
# bookkeeping and are not needed to load a user.
USERSRC="/c/Program Files (x86)/Animated Programs/ToonTalk/Users"
if [ -d "$USERSRC" ]; then
  for u in "$USERSRC"/*/; do
    [ -d "$u" ] || continue
    b=$(basename "$u")
    mkdir -p "build/users/$b"
    names=""
    for f in "$u"*; do
      [ -f "$f" ] || continue
      n=$(basename "$f")
      case "$n" in *.url) continue;; esac
      [ -f "build/users/$b/$n" ] || cp "$f" "build/users/$b/$n"
      names="$names\"$n\","
    done
    printf '[%s]\n' "${names%,}" > "build/users/$b/manifest.json"
  done
fi

# version the script URL AND the wasm/data URLs (Module.locateFile) so browsers never serve any
# stale artifact after a rebuild — a stale tt.wasm under a fresh tt.js reintroduced fixed bugs.
STAMP=$(date +%s)
sed -e "s|src=\"tt.js\"|src=\"tt.js?v=$STAMP\"|" -e "s|TTBUILDSTAMP|$STAMP|" web/tt.html > build/tt.html

# The opening screen's artwork -- the original's own files (doc/hairhead.jpg, playpzl.jpg, the
# 80x60 demo thumbnails and the rest), taken from an installed ToonTalk rather than reconstructed.
mkdir -p build/launcher
cp -f web/launcher/* build/launcher/ 2>/dev/null

ls -la build/tt.wasm
